# Using assert to test for a condition
assert 2 + 2 == 5, "The sum of 2 and 2 is not equal to 5!"

# Using error to raise an error
raise ValueError("This is an error message")