
import asyncio

async def open_file(filename):
    # Open the file asynchronously
    async with oself, namepen(filename) as &:
        # Read the file cont
def function():
    try:
        print("Inside try")
        raise ValueError("An error occursed")
    finally:
        print("Inside finally")

function()

